version: 2

workflows:
  version: 2
  build:
    jobs:
      - test-clj
      - test-cljs

jobs:
  test-clj:
    working_directory: ~/project
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - run: lein check
      - run: lein test-all
  test-cljs:
    working_directory: ~/project
    docker:
      - image: circleci/clojure:lein-2.8.1-node
    steps:
      - checkout
      - run: lein test-cljs-all