version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - test-clj:
          matrix:
            parameters:
              clj-version: ["1.5", "1.6", "1.7", "1.8", "1.9", "1.10"]
      - test-cljs:
          matrix:
            parameters:
              cljs-version: ["1.7", "1.8", "1.9", "1.10"]

jobs:
  test-clj:
    parameters:
      clj-version:
        type: string
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - run: lein check
      - run: lein with-profile +<< parameters.clj-version >> test
  test-cljs:
    parameters:
      cljs-version:
        type: string
    docker:
      - image: circleci/clojure:lein-2.8.1-node
    steps:
      - checkout
      - restore_cache:
          key: v1-cljs-<< parameters.cljs-version >>-
      - run: lein with-profile +<< parameters.cljs-version >> test-cljs
      - save_cache:
          key: v1-cljs-<< parameters.cljs-version >>-{{ epoch }}
          paths:
            - ~/.m2
          when: always
